development:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { 'localhost' } %>
  aws_files_bucket: <%= ENV['AWS_PLATFORM_FILES_BUCKET'] %>
  aws_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV.fetch('AWS_REGION') { 'us-east-1' } %>
  canvas_url: <%= ENV.fetch('CANVAS_URL') { 'http://canvasweb:3000/' } %>
  canvas_cloud_url: <%= ENV.fetch('CANVAS_CLOUD_URL') { 'https://braven.instructure.com' } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV.fetch('MAILER_FROM_EMAIL') { 'noreply@bebraven.org' } %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  linked_in_client_id: <%= ENV.fetch('LINKED_IN_CLIENT_ID') %>
  linked_in_client_secret: <%= ENV.fetch('LINKED_IN_CLIENT_SECRET') %>
  lrs_url: <%= ENV['LRS_URL'] %>
  lrs_auth_token: <%= ENV['LRS_AUTH_TOKEN'] %>
  lti_launch_remember_for: <%= ENV.fetch('LTI_LAUNCH_REMEMBER_FOR') { '2.weeks' } %>
  # This value comes from here: https://canvas.instructure.com/doc/api/file.lti_dev_key_config.html#launch-overview
  lti_oidc_base_uri: <%= ENV.fetch('LTI_OIDC_BASE_URI') { 'https://canvas.instructure.com' } %>
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  join_base_url: <%= ENV.fetch('JOIN_BASE_URL') { 'http://joinweb:3001' } %>
  join_api_token: <%= ENV.fetch('JOIN_API_TOKEN') { 'some_random_key' } %>

test:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { 'localhost' } %>
  aws_files_bucket: <%= ENV.fetch('AWS_PLATFORM_FILES_BUCKET') { 'your-bucket-name' } %>
  aws_access_key: <%= ENV.fetch('AWS_ACCESS_KEY_ID') { 'AKIA55555555555555FM' } %>
  aws_secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') { 'sXY55555555555555555555555555555555S/ZAu' } %>
  aws_region: <%= ENV.fetch('AWS_REGION') { 'us-east-1' } %>
  canvas_url: <%= ENV.fetch('CANVAS_URL') { 'http://example.portal.com/' } %>
  canvas_cloud_url: <%= ENV.fetch('CANVAS_CLOUD_URL') { 'https://example.instructuredomain.com' } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  linked_in_client_id: <%= ENV.fetch('LINKED_IN_CLIENT_ID') %>
  linked_in_client_secret: <%= ENV.fetch('LINKED_IN_CLIENT_SECRET') %>
  lrs_url: <%= ENV.fetch('LRS_URL') { 'https://example.lrs.com/data/xAPI' } %>
  lrs_auth_token: <%= ENV.fetch('LRS_AUTH_TOKEN') { 'some_basic_auth_token_for_lrs_xapi_statements' } %>
  lti_launch_remember_for: <%= ENV.fetch('LTI_LAUNCH_REMEMBER_FOR') { '1.day' }  %>
  lti_oidc_base_uri: 'https://example.lms.com'
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  join_base_url: <%= ENV.fetch('JOIN_BASE_URL') { 'http://joinweb:3001' } %>
  join_api_token: <%= ENV.fetch('JOIN_API_TOKEN') { 'some_random_key' } %>

staging:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { nil } %>
  aws_files_bucket: <%= ENV['AWS_PLATFORM_FILES_BUCKET'] %>
  aws_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV.fetch('AWS_REGION') { 'us-east-1' } %>
  canvas_url: <%= ENV.fetch('CANVAS_URL') { 'https://stagingportal.bebraven.org/' } %>
  canvas_cloud_url: <%= ENV.fetch('CANVAS_CLOUD_URL') { 'https://braven.instructure.com' } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  linked_in_client_id: <%= ENV.fetch('LINKED_IN_CLIENT_ID') %>
  linked_in_client_secret: <%= ENV.fetch('LINKED_IN_CLIENT_SECRET') %>
  lrs_url: <%= ENV['LRS_URL'] %>
  lrs_auth_token: <%= ENV['LRS_AUTH_TOKEN'] %>
  lti_launch_remember_for: <%= ENV.fetch('LTI_LAUNCH_REMEMBER_FOR') { '2.weeks' }  %>
  lti_oidc_base_uri: <%= ENV.fetch('LTI_OIDC_BASE_URI') { 'https://canvas.instructure.com' } %>
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  join_base_url: <%= ENV.fetch('JOIN_BASE_URL') { 'http://joinweb:3001' } %>
  join_api_token: <%= ENV.fetch('JOIN_API_TOKEN') { 'some_random_key' } %>

production:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { nil } %>
  aws_files_bucket: <%= ENV['AWS_PLATFORM_FILES_BUCKET'] %>
  aws_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV.fetch('AWS_REGION') { 'us-east-1' } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  canvas_url: <%= ENV.fetch('CANVAS_URL') { 'https://portal.bebraven.org/' } %>
  canvas_cloud_url: <%= ENV.fetch('CANVAS_CLOUD_URL') { 'https://braven.instructure.com' } %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  linked_in_client_id: <%= ENV.fetch('LINKED_IN_CLIENT_ID') %>
  linked_in_client_secret: <%= ENV.fetch('LINKED_IN_CLIENT_SECRET') %>
  lrs_url: <%= ENV['LRS_URL'] %>
  lrs_auth_token: <%= ENV['LRS_AUTH_TOKEN'] %>
  lti_launch_remember_for: <%= ENV.fetch('LTI_LAUNCH_REMEMBER_FOR') { '2.weeks' } %>
  lti_oidc_base_uri: <%= ENV.fetch('LTI_OIDC_BASE_URI') { 'https://canvas.instructure.com' } %>
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  join_base_url: <%= ENV.fetch('JOIN_BASE_URL') { 'http://joinweb:3001' } %>
  join_api_token: <%= ENV.fetch('JOIN_API_TOKEN') { 'some_random_key' } %>
