class CreateFields < ActiveRecord::Migration[6.0]
  def up
    create_table :fields do |t|
      t.string :name

      t.timestamps
    end

    fields = [
      'Accounting',
      'Actuarial Science',
      'Advertising',
      'Aerospace',
      'African American Studies',
      'African Studies',
      'Agriculture',
      'American Indian Studies',
      'American Studies',
      'Anatomy',
      'Animation',
      'Anthropology',
      'Archaeology',
      'Architecture',
      'Art History',
      'Asian American Studies',
      'Asian Studies',
      'Astronomy',
      'Banking',
      'Beauty / Cosmetics',
      'Biology',
      'Biomedical Engineering',
      'Biotechnology',
      'Business',
      'Cartography',
      'Chemical',
      'Chemical Engineering',
      'Chemistry',
      'Child Development',
      'Civil Engineering',
      'Cognitive Science',
      'Communications',
      'Computer Engineering',
      'Computer Hardware',
      'Computer Hardware Engineering',
      'Computer Science',
      'Construction Trades',
      'Creative Writing',
      'Criminal Justice',
      'Criminology',
      'Culinary Arts',
      'Dance',
      'Diversity Studies',
      'Ecology',
      'Economics',
      'Education',
      'Electrical Engineering',
      'Electronics',
      'Employment / Human Resources',
      'Energy',
      'English / Literature',
      'Environmental Studies',
      'Equestrian Studies',
      'European Studies',
      'Fashion',
      'Film',
      'Financial Services',
      'Fine Arts',
      'Food & Beverage',
      'Food Science',
      'Foreign Language',
      'Gay and Lesbian Studies',
      'Gender Studies',
      'Genetics',
      'Geography',
      'Graphic Design',
      'Health',
      'History',
      'Hospitality',
      'Human Biology',
      'Human Resources',
      'Human Services',
      'Industrial Engineering',
      'Information Technology',
      'Insurance',
      'Interior Design',
      'Journalism',
      'Journalism / News / Media',
      'Landscape Architecture',
      'Latin American Studies',
      'Latinx Studies',
      'Law',
      'Law / Legal Studies',
      'Library Science',
      'Management / Strategic Consulting',
      'Manufacturing',
      'Marine Sciences',
      'Maritime Studies',
      'Marketing',
      'Math',
      'Mechanical Engineering',
      'Medical Devices & Supplies',
      'Medicine',
      'Military',
      'Music',
      'Neurosciences',
      'Nursing',
      'Nutrition',
      'Performing Arts',
      'Pharmaceutical',
      'Philosophy',
      'Physics',
      'Political Science',
      'Psychology',
      'Public Administration',
      'Public Health',
      'Public Relations',
      'Publishing',
      'Real Estate',
      'Religion',
      'Social Work',
      'Sociology',
      'Software Engineering',
      'Sports',
      'Sports and Fitness',
      'Statistics',
      'Technology',
      'Telecommunications',
      'Theater',
      'Theology',
      'Tourism',
      'Transportation / Travel',
      'Urban Planning',
      'Urban Studies',
      'Visual Arts',
      'Women\'s Studies',
      'Writing'
    ].sort

    tuples = fields.map { |i| "(#{ActiveRecord::Base.connection.quote(i)}, '#{Time.now}', '#{Time.now}')" }
    tuples_as_sql = ActiveRecord::Base::sanitize_sql(tuples.join(', '))
    execute "INSERT INTO fields (name, created_at, updated_at) VALUES #{tuples_as_sql}"
  end

  def down
    drop_table :fields
  end
end
